### PR TITLE
Delete for BST

### PR DESCRIPTION
**Pull request by goyaljai**
please review. thanks

### CODE REVIEW

**Comment by xorz57** [comment]
Can you move the contributed code to another branch with your changes? Adding code directly into the master branch is getting worse for me to review your changes and test them. Yeah, you have to test if node the node removal works correctly and prove it. I will create separate issues for the node deletion operation be sure to check them out! The initial issue was a bit too big to cover.

**Comment by goyaljai** [comment]
sure

**Comment by xorz57** [comment]
@goyaljai create a branch (name it whatever you want) on the develop branch. That would be better. I don't mean to frustrate you telling you to change branches but it helps a lot if we keep branches clean!

**Comment by goyaljai** [comment]
@xorz57 I am not able to do this. I am not that well versed with git. can you help me. thanks

**Comment by xorz57** [comment]
Don't be disappointed! I have struggled a lot with git. I can recommend you a software that will make git and GitHub a lot easier for you. It's called [GitKraken](https://www.gitkraken.com/). What I was trying to tell you is the following. When you have a repository where there are lots of people involved and not just you (the author) you basically follow a strategy (workflow) that requires having 2 branches (a master and a develop). There is one important rule. We never push code to master or develop directly. We always create a branch on the develop branch with our changes and then merge it back to the develop. After enough changes are made we merge develop into master. That is the [GIT-flow](http://nvie.com/posts/a-successful-git-branching-model/).

What I wanted from you
- Clone forest repo into your computer.
- Switch to the develop branch.
- Create a branch (call it whatever you like) on the develop branch.
- Commit your code on that branch.
- Start a pull request from that branch to the develop branch of the original project.

I hope this helps out somehow.

**Comment by goyaljai** [comment]
thanks a lot. I will do in next 10mins thanks

**Pull request closed without merging**
