### PR TITLE
[CMake] Use targets, build and install files

### PR DESCRIPTION
**Pull request by light2yellow**
Use target-based approach to build, install and test forest.

`sudo make install` installs the library and CMake-related files. I have tested it in an unrelated directory in a project with such listfile:

```cmake
cmake_minimum_required(VERSION 3.9)

add_executable(test_forestlib example_avl_tree.cpp)

find_package(forest REQUIRED CONFIG)

target_link_libraries(
    test_forestlib
        PRIVATE
          Forest::forest)
```

* binaries are now under `bin`
* `tests` executable was renamed to `forestTests`
* license notices were populated (I recommend doing it on every file in the repository)
* headers were moved deeper

~~This requires #49 to be merged.~~

This PR more or less implements the desired behaviour. Feel free to discuss if you don't like anything.

I'm also going to make few more PRs that will implement some CMake-related features: detecting version from git, building doxygen documentation, compile flags etc. They might or might not be based one on another, like these.

References: #48.

### CODE REVIEW

**Comment by xorz57** [comment]
@light2yellow Looks really good so far! 👍 I am reviewing it right now.

**Comment by light2yellow** [comment]
Sorry, probably shouldn't have resolved it myself...

**Comment by light2yellow** [comment]
Anyway, you can `merge --squash` it, right? I don't have much experience with "clean" git strategies.

**Comment by xorz57** [comment]
@light2yellow Don't worry I will take care of that! I am using an enterprise software for git so even if merge conflicts exist I can solve them easier. I have only one question. Would you agree with the idea to rename the inner forest folder to something more familiar like include? If you do, how would you change the install command to install the library for macOS and linux?

**Comment by light2yellow** [comment]
> Would you agree with the idea to rename the inner forest folder to something more familiar like include?

Right, it would make more sense to name the directory `src` or `include`.

> If you do, how would you change the install command to install the library for macOS and linux?

I'll try and see if there's need to do so :) I can also try to reduce the amount of directories, putting `.h` files back from the inner `include` directory (currently) to the outer [renamed from inner `forest`] `include` directory.

**Comment by xorz57** [comment]
@light2yellow Yeah something more like
`ProjectDirectory/include` instead of `ProjectDirectory/forest/include/forest`
Let me know if you are able to simplify the folder structure.

**Comment by light2yellow** [comment]
Yeah, I've tried a few things. It will be fine after the headers are installed, but for the examples to build I need a few more things to do. Working on it.

**Comment by xorz57** [comment]
@light2yellow Yeah ok, take your time! I think you understand what I meant with "keep the folder structure simple". I know you can make a very well organized structure 🥇.

**Comment by light2yellow** [comment]
Looks better now. I also retested as downstream.

**Comment by xorz57** [comment]
```
$ sudo make install
[sudo] password for xorz57: 
[ 14%] Built target example_splay_tree
[ 28%] Built target example_red_black_tree
[ 42%] Built target example_avl_tree
[ 57%] Built target example_binary_search_tree
[100%] Built target forestTests
Install the project...
-- Install configuration: "Debug"
-- Installing: /usr/lib/cmake/forest/forestTargets.cmake
-- Installing: /usr/lib/cmake/forest/forestConfig.cmake
-- Installing: /usr/lib/cmake/forest/forestConfigVersion.cmake
-- Installing: /usr/local/include/forest/avl_tree.h
-- Installing: /usr/local/include/forest/binary_search_tree.h
-- Installing: /usr/local/include/forest/red_black_tree.h
-- Installing: /usr/local/include/forest/splay_tree.h
```

Why build the example files and tests when the user just wants to install the header files?

**Comment by light2yellow** [comment]
Because `sudo make install` makes sure target `all` is built and ready to be installed. Targets declared normally implicitly depend on `all`. I will provide variables that will build examples and test based on a variable.

I will also need some place to document them. I'll do this in README just for now.

**Comment by xorz57** [comment]
```
.
├── circle.yml
├── cmake
│   └── modules
│       └── ForestBuildType.cmake
├── CMakeLists.txt
├── CODE_OF_CONDUCT.md
├── CONTRIBUTING.md
├── doc
│   └── Doxyfile
├── Dockerfile
├── examples
│   ├── CMakeLists.txt
│   ├── example_avl_tree.cpp
│   ├── example_binary_search_tree.cpp
│   ├── example_red_black_tree.cpp
│   └── example_splay_tree.cpp
├── include
│   ├── avl_tree.h
│   ├── binary_search_tree.h
│   ├── cmake
│   │   └── forestConfig.cmake
│   ├── CMakeLists.txt
│   ├── red_black_tree.h
│   └── splay_tree.h
├── LICENSE
├── README.md
└── tests
    ├── catch.hpp
    ├── CMakeLists.txt
    ├── test_avl_tree.cpp
    ├── test_binary_search_tree.cpp
    ├── test.cpp
    ├── test_red_black_tree.cpp
    └── test_splay_tree.cpp

7 directories, 27 files
```
Another question. Is it possible to have only one cmake folder? Can the include folder be more clean?

**Comment by light2yellow** [comment]
Addressed :)

**Comment by xorz57** [comment]
@light2yellow May I ask whats the purpose of the following two files?
```
├── cmake
│   └── modules
│       ├── ForestBuildType.cmake
│       └── forestConfig.cmake
```
and why do we need both of them?
If you could just create one somehow you should propably want to show off your cmake module for this library to the [cmake repository](https://github.com/Kitware/CMake/tree/master/Modules).

**Comment by light2yellow** [comment]
> whats the purpose of the following two files?

The first one sets the default build type in case none was specified. Not required, but desired to exist. You can read on build types [here](https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html). Usually it sets these flags:

```cmake
# CMAKE_CXX_FLAGS_DEBUG is -g
# CMAKE_CXX_FLAGS_RELEASE is -O3 -DNDEBUG
# CMAKE_CXX_FLAGS_RELWITHDEBINFO is -O2 -g -DNDEBUG
# CMAKE_CXX_FLAGS_MINSIZEREL is -Os -DNDEBUG
```

 The second one is used to find `forest` by downstream. The fact that it contains "only" one line is due to no external dependencies of `forest`. If there were any, it wouldn't be less trivial to make sure they are found when downstream configures their CMake project, but possible. And the listfiles provided make it easily extensible in case `forest` obtains any dependencies in future, so I'd better leave it as it is. The number of files isn't really important, is it?

> you should propably want to show off your cmake module for this library to the cmake repository

no, `*Config`s are not sent to Kitware, but remain upstream's obligation ("upstream" being `forest`).

**Comment by xorz57** [comment]
@light2yellow If you would like this pull request to be merged point to the develop branch I will merge it and then make the changes stated in the review.

**Comment by light2yellow** [comment]
> Why are those .cmake files installed into the lib directory of the end user?

It is considered a common practice as it will be near the top of the default directories for CMake to traverse when looking for config. See [cmake-packages(7)](https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html).

> And why is this still in release mode when installing?

Not sure I understand. Did you mean `CMAKE_BUILD_TYPE=Release` when wrote "release mode"? Please elaborate on how you want the installation to behave.

**Comment by light2yellow** [comment]
As of right now,

```
$ cmake -GNinja -DFOREST_ENABLE_TESTING=ON -DFOREST_BUILD_EXAMPLES=ON -DFOREST_BUILD_DOCUMENTATION=ON ..
$ sudo ninja install
```
will install headers and CMake package configuration files into appropriate folders, independently of `CMAKE_BUILD_TYPE`. It also doesn't provide any additional `install`-like targets for component-wise installation.

**Comment by xorz57** [comment]
@light2yellow

> Not sure I understand. Did you mean CMAKE_BUILD_TYPE=Release when wrote "release mode"? Please elaborate on how you want the installation to behave.

I think release mode should be the default build type for the examples and testing instead of debug mode.

**Comment by xorz57** [comment]
Thanks for your collaboration @light2yellow 💯

**Comment by light2yellow** [comment]
@xorz57 thank you, too.

One thing to note, though: the version is already set to 4.2.1 (as I saw a master hotfix merge) [here](https://github.com/xorz57/forest/blob/develop/CMakeLists.txt#L3) and you should bump it whenever you tag a new release.

It is possible to populate version through git tags, though. I can provide it, if you want so. Otherwise you should _not forget to update the version there_, as CMake package config version and Doxygen docs version rely on it.

Does `forest` have any `#define` that would pass version to the source code? It's possible to make it so that everything is auto-generated from git tags - if current commit is a release version, `<major>.<minor>.<patch>` is used to describe the version, otherwise `<major>.<minor>.<patch>-g<sha>`. And different combinations of it. Not sure if you're interested in it.

**Comment by xorz57** [comment]
@light2yellow Nice! That's great!

> One thing to note, though: the version is already set to 4.2.1 (as I saw a master hotfix merge) here and you should bump it whenever you tag a new release.

Thanks for pointing out that I have to pump up the version number, I didn't notice that at first.

> Does forest have any #define that would pass version to the source code?

No, Forest does not have any `#define` that states the version of the library for the moment.

> It's possible to make it so that everything is auto-generated from git tags - if current commit is a release version, <major>.<minor>.<patch> is used to describe the version, otherwise <major>.<minor>.<patch>-g<sha>

Yeah sure! The tag format I use is <major>.<minor>.<patch>. Let me know if you have something in mind.

**Pull request merged**
