### PR TITLE
Replace raw pointers with smart pointers #8

### PR DESCRIPTION
**Pull request by MatusKysel**

### CODE REVIEW

**Comment by MatusKysel** [comment]
Done!

**Comment by xorz57** [comment]
Red Black Tree and Binary Search Tree pass all tests! THATS GREAT👍 
Splay Tree though gives me some errors.
Can you fix them?
Here is the output of my compiler (Apple clang)

Image

**Comment by MatusKysel** [comment]
If you do not mind, I will close and reopen this pullreq, because I really want that Tshirt and they are counting pullreq after 1st of October

**Comment by xorz57** [comment]
Yup no problem 👍

**Pull request closed without merging**
