### PR TITLE
delete in bst

### PR DESCRIPTION
**Pull request by goyaljai**
Please check, am I able to do? @xorz57

### CODE REVIEW

**Comment by xorz57** [comment]
@goyaljai This is a proper pull request yes! I am not so sure though about your implementation...

**Comment by goyaljai** [comment]
please post the errors I'll try to rectify them. thanks

**Comment by xorz57** [comment]
After you make changes to the source code you must
- Check if the build succeeds without error
  (and yes post here the error messages if you need help)
- Create test cases to verify the validity of your code segments

To build the examples and the unit tests run the following commands while at the project root.

```
$ mkdir build
$ cd build
$ cmake ..
& make
```

Only if you pass all the test cases (including the ones you made) and the example files compile will the pull request be merged. I will clarify this proceedure in the project later.

**Comment by xorz57** [comment]
@goyaljai Are you still working on this PR?

**Pull request closed without merging**
