### PR TITLE
Cmake builds, Docker, and CI

### PR DESCRIPTION
**Pull request by JLospinoso**
Implements #17 #19 and #20 

1. You can now build from a Docker container (see Dockerfile)
2. Build runs on CircleCI, but you can extend to other platforms easily now (because Docker..)
3. You'll want to set up your own CircleCI account to manage builds--right now it's working off my fork (https://circleci.com/gh/JLospinoso/forest)
4. I added a badge to README, update the URL as appropriate once you've got your account
5. Examples and tests now build

### CODE REVIEW

**Comment by xorz57** [comment]
@JLospinoso Sir. You did a hell of a job !!! 🍻

**Comment by JLospinoso** [comment]
@xorz57 Please add hacktoberfest label to this PR :)

**Comment by xorz57** [comment]
The changes you made are on the master branch right? Will this be a problem or not at all? I am new to GitHub and am trying my best learning how things work.

**Comment by xorz57** [comment]
Added the label as requested ;)

**Pull request merged**
